AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:  #   Type: String
  Environment:
    Type: String
Resources:
  # =========================================================================================
  # AWS LAMBDA FUNCTIONS
  # ========================================================================================= 
  BranchCollector:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: BranchCollector.yml
      Parameters: 
        Environment: !Ref Environment
    # DependsOn: 
    #   - IAM
    #   - Queues

  SalespersonCollector:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: SalespersonCollector.yml
      Parameters: 
        Environment: !Ref Environment
    # DependsOn: 
    #   - IAM
    #   - Queues
 
  SaleCollector:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: SaleCollector.yml
      Parameters: 
        Environment: !Ref Environment
    # DependsOn: 
    #   - IAM
    #   - Queues